### ISSUE TITLE
Scroll floating button

### ISSUE THREAD

**Issue by JairDavid** [HectorSaldes/liber#1]
### Better UX
Add a floating button to get back to the top search and focus on the search input **(improvements for UX)**, it can be something like green button:

![image](https://user-images.githubusercontent.com/67834146/172982633-847e7d0f-3fcd-4da4-9a2a-db61753e6c54.png)

![image](https://user-images.githubusercontent.com/67834146/172983641-6403446a-793a-4049-81d9-ec7dd435fe54.png)

### Why this?
As you can see, when we have a big scroll down, we have to scroll up the same way (it can be annoying and tiresome for the user)

![image](https://user-images.githubusercontent.com/67834146/172983170-4fea85fc-5b12-4dc3-963f-c143fc3cbc24.png)

**Comment by HectorSaldes** [comment]
We have added this new feature @JairDavid thanks a lot for your feedback
